"""empty message

Revision ID: 32a3cefd30f6
Revises: 89cc59802417
Create Date: 2020-05-11 14:42:23.777583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a3cefd30f6'
down_revision = '89cc59802417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevant_page_numbers', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.drop_column('relevant_page_numbers')

    # ### end Alembic commands ###
