"""empty message

Revision ID: 89cc59802417
Revises: e7248806c0c8
Create Date: 2020-05-05 11:01:34.474008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cc59802417'
down_revision = 'e7248806c0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_pages', sa.Integer(), nullable=True))

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transcription1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transcription2', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('transcription2')
        batch_op.drop_column('transcription1')
        batch_op.drop_column('num_pages')
        batch_op.drop_column('notes2')
        batch_op.drop_column('notes1')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('image_pages')

    # ### end Alembic commands ###
