"""empty message

Revision ID: e7248806c0c8
Revises: 39119815b311
Create Date: 2020-04-20 20:52:46.270493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7248806c0c8'
down_revision = '39119815b311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('transcription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
